### ISSUE TITLE
(No output on stdout) stderr: Can't locate Data/Validate/Domain.pm

### ISSUE THREAD

**Issue by Mies-bvd89** [matteocorti/check_rbl#11]
OS: CentOS 7.X
Code version: 1.3.8

Installation completed without errors.

Error code Nagios Core:
(No output on stdout) stderr: Can't locate Data/Validate/Domain.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/nagios/libexec/check_rbl line 30.
BEGIN failed--compilation aborted at /usr/local/nagios/libexec/check_rbl line 30. 
Performance Data: 

Error code when running with user account:
None, everything is fine.

**Comment by matteocorti** [comment]
The perl interpreter is not able to find the perl module Data::Validate::Domain

You need to install it: either directly from CPAN or by finding someone that did an RPM for Centos
