### ISSUE TITLE
Issue with spamcannibal.org

### ISSUE THREAD

**Issue by rpv-tomsk** [matteocorti/check_rbl#18]
Hi, Matteo!

At the moment of writing, there is an issue with `spamcannibal.org` - domain ownership not renewed and outdated.

```
# dnstracer -4s . spamcannibal.org
Tracing to spamcannibal.org[a] via A.ROOT-SERVERS.NET, maximum of 3 retries
A.ROOT-SERVERS.NET [.] (198.41.0.4)
 |\___ d0.org.afilias-nst.org [org] (2001:0500:000f:0000:0000:0000:0000:0001) Not queried
 |\___ d0.org.afilias-nst.org [org] (199.19.57.1)
 |     |\___ ns2.renewyourname.net [spamcannibal.org] (64.98.148.18) Got authoritative answer
 |      \___ ns1.renewyourname.net [spamcannibal.org] (64.99.97.38) Got authoritative answer
```
Due to this, it began to respond with a stub address to any request.

```
# host wwww.www.spamcannibal.org
wwww.www.spamcannibal.org has address 91.195.240.117
# host wwww.www.bl.spamcannibal.org
wwww.www.bl.spamcannibal.org has address 91.195.240.117
```

Perhaps we should keep watch over him a bit.

I do not know why I'm writing this here, I think you already know this while using the plugin ... 
Probably just out of habit.  ;-)

Regards, 
Pavel.

**Comment by HOSTED-POWER** [comment]
I'm seeing the same, suddenly ALL our servers come out as blacklisted, what is going on?

**Comment by HOSTED-POWER** [comment]
Some debug output:

/usr/lib/nagios/plugins/./check_rbl -H 83.96.202.212 -s bl.spamcannibal.org -v -d

[DBG] validate(83.96.202.212, 83.96.202.212)
Using 15 as global script timeout
Checking 83.96.202.212 (83.96.202.212) on 1 server(s)
[DBG] reading...212.202.96.83.bl.spamcannibal.org
[DBG] name = 212.202.96.83.bl.spamcannibal.org, outstanding = 1
[DBG] reading...EOF.
[DBG] waiting for replies
[DBG] replies received: 1
[DBG] handling a reply
[DBG] Processing answer
[DBG] host = 91.195.240.117
[DBG] callback( 212.202.96.83.bl.spamcannibal.org, 91.195.240.117 )
[DBG] callback( 212.202.96.83.bl.spamcannibal.org, 91.195.240.117 )
listed in bl.spamcannibal.org as 91.195.240.117
[DBG] outstanding = 0, eof = 1
CHECK_RBL CRITICAL - 83.96.202.212 BLACKLISTED on 1 server of 1 (bl.spamcannibal.org) | servers=1;0;0 time=0s;;

We saw the same problem with dnsbl.cyberlogic.net some days ago, suddenly all servers came out as blacklisted while they were not. We have no clue why this is happening all the sudden.

**Comment by BRVN01** [comment]
I noticed the same problem for you, when you test the database, it blocks all domains.

./check_rbl -H uol.com.br -t 60 -c 1 -w 1 -s bl.spamcannibal.org
CHECK_RBL CRITICAL - uol.com.br BLACKLISTED on 1 server of 1 (bl.spamcannibal.org) | servers=1;0;0 time=0s;;

./check_rbl -H facebook.com.br -t 60 -c 1 -w 1 -s bl.spamcannibal.org
CHECK_RBL CRITICAL - facebook.com.br BLACKLISTED on 1 server of 1 (bl.spamcannibal.org) | servers=1;0;0 time=0s;;

./check_rbl -H goole.com.br -t 60 -c 1 -w 1 -s bl.spamcannibal.org
CHECK_RBL CRITICAL - goole.com.br BLACKLISTED on 1 server of 1 (bl.spamcannibal.org) | servers=1;0;0 time=0s;;

**Comment by matteocorti** [comment]
It seems that spamcannibal.org is not working. Looking up an IP on the web page delivers

```
could not connect to Daemon at ../blib/lib/Mail/SpamCannibal/BDBclient.pm (autosplit into ../blib/lib/auto/Mail/SpamCannibal/BDBclient/_unsock.al) line 61.
```

I will remove it from the documentation for the time being

**Comment by matteocorti** [comment]
Closed with 1.4.3

**Comment by HOSTED-POWER** [comment]
Hmm are you sure? Because it works on some online blacklist checks? Also it's very strange we had EXACTLY the same issue with  dnsbl.cyberlogic.net

If there is a problem with the blacklist your plugin shouldn't mark them as blacklisted. We got 100's of false alerts for all our servers, it was a real mess!!

**Comment by matteocorti** [comment]
My plugin just checks what a user specifies. The list is just a suggestion. I have no way to know is as DNS request is delivering the correct value. I just removed the two checks from the example list.

**Comment by HOSTED-POWER** [comment]
So what I mean is that it's really cumbersome your plugin says blacklisted, it should just make a remark that checking this blacklist failed. When another list is failing temporary it would have the same effect.

Do you mean there is no clue? Why isn't a tool like mxtoolbox not failing on it? 

I can agree you cannot be responsible for non working blacklist, but than marking the result as blacklisted is really hell for us!

PS: We specify our own blacklists. Failing doesn't mean this should return as blacklisted. It's very very messy and disaster on temporary failures if you have 100's of server ip's monitored

**Comment by matteocorti** [comment]
mxtoolbox is not using spamcannibal: https://mxtoolbox.com/SuperTool.aspx?action=mx%3auol.com.br&run=toolpage

**Comment by matteocorti** [comment]
A DNS query deliver a binary result: blacklisted or not. All these services are working like that either the DNS is resolved or not.

**Comment by HOSTED-POWER** [comment]
Hmm you're right, I didn't check it I think then.

However I checked here for dnsbl.cyberlogic.net and it was not failing while on the server with this check it was :/ 

https://www.dnsbl.info/dnsbl-database-check.php

Atm this blacklist is working perfectly again! I'm not sure if the cause was the same, but very annoying.

Isn't there any way to see the check simply fails? :)

**Comment by matteocorti** [comment]
All these blacklists are using DNSBL (https://en.wikipedia.org/wiki/DNSBL). It works by doing a special DNS query (with the reversed IP address prepended to the one of the provider). If an A record is returned it's blacklisted, if nothing is returned than is not.

As I get only these two options I have no other choice then to follow the RFC 5782.
