### ISSUE TITLE
ipv6 blacklisted but cannot find it in blacklist

### ISSUE THREAD

**Issue by HOSTED-POWER** [matteocorti/check_rbl#19]
Hello,

We checked these ip agains ipv6 rbl all.s5h.net

2a04:3544:1000:1510:3cc8:64ff:fefa:6400
2a04:3544:1000:1510:3cc8:64ff:fefa:7bbc

It gives blacklisted status, however if we query the blacklist, we're not on it ...

We even have some more false positives since this morning.

How is this possible?

**Comment by HOSTED-POWER** [comment]
any idea? we still have multiple hosts suffering from it atm ...

**Comment by HOSTED-POWER** [comment]
Daily we add new hosts which are not on this blacklist when we check it, however check_rbl says otherwise. Anything we could do to fix?

**Comment by scuben** [comment]
did you check the debug information ("-d" flag)

**Comment by HOSTED-POWER** [comment]
I just tried, but no idea:

/usr/lib/nagios/plugins/check_rbl -s all.s5h.net -H 2a04:3544:1000:1510:3cc8:64ff:fefa:c56 -d
[DBG] validate(2a04:3544:1000:1510:3cc8:64ff:fefa:c56, 2a04:3544:1000:1510:3cc8:64ff:fefa:c56)
[DBG] reading...6.5.c.0.a.f.e.f.f.f.4.6.8.c.c.3.0.1.5.1.0.0.0.1.4.4.5.3.4.0.a.2.all.s5h.net
[DBG] name = 6.5.c.0.a.f.e.f.f.f.4.6.8.c.c.3.0.1.5.1.0.0.0.1.4.4.5.3.4.0.a.2.all.s5h.net, outstanding = 1
[DBG] reading...EOF.
[DBG] waiting for replies
[DBG] replies received: 1
[DBG] handling a reply
[DBG] Processing answer
[DBG] host = 127.0.0.2
[DBG] callback( 6.5.c.0.a.f.e.f.f.f.4.6.8.c.c.3.0.1.5.1.0.0.0.1.4.4.5.3.4.0.a.2.all.s5h.net, 127.0.0.2 )
[DBG] callback( 6.5.c.0.a.f.e.f.f.f.4.6.8.c.c.3.0.1.5.1.0.0.0.1.4.4.5.3.4.0.a.2.all.s5h.net, 127.0.0.2 )
[DBG] outstanding = 0, eof = 1
CHECK_RBL CRITICAL - 2a04:3544:1000:1510:3cc8:64ff:fefa:c56 BLACKLISTED on 1 server of 1 (all.s5h.net) | servers=1;0;0 time=0s;;

**Comment by scuben** [comment]
Looks like check_rbl is doing its job and somehow the ip is listed in the dns. I think there is not much that check_rbl can do here.

**Comment by HOSTED-POWER** [comment]
this is strange: 

[DBG] Processing answer
[DBG] host = 127.0.0.2

I don't see that when checking other ipv6 ip's, is it normal?

**Comment by scuben** [comment]
If the ip is not blacklisted then this is normal that those two lines do not show.

**Comment by HOSTED-POWER** [comment]
You are right, it was found. Very strange we cannot remove it trough curl as they suggest :/

In any case you can close the issue here and thanks a lot for your support!
