### ISSUE TITLE
Can't install with ubuntu 18.04

### ISSUE THREAD

**Issue by JMBokhorst** [matteocorti/check_rbl#21]
Hi, 

I wanted to install this plugin, as it would be really helpful for me. 

However I have an issue with the following dependency: libnagios-plugin-perl, as there is no candidate for the latest ubuntu 18.04 (https://packages.ubuntu.com/search?keywords=libnagios-plugin-perl). 

Do you have a suggestion how to get this plugin installed and working on ubuntu 18.04?

**Comment by matteocorti** [comment]
Hi
The dependency is not from the plugin but most likely from your package. Did you try to install the source? Does it work?
Matteo
