### ISSUE TITLE
stderr: Can't locate Data/Validate/Domain.pm

### ISSUE THREAD

**Issue by esetman** [matteocorti/check_rbl#23]
Hi,
I have CentOS 7 and nagios. 
plugin have problem:
(No output on stdout) stderr: Can't locate Data/Validate/Domain.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/nagios/libexec/check_rbl line 25. 

file Domain.pm exist
if I run script manualy Its OK: ./check_rbl -H XXX.XXX.XXX.XXX -t 60 -c 1 -w 1 -s cbl.anti-spam.org.cn 
if nagios check script, its PROBLEM.

some idea? Thank you

**Comment by matteocorti** [comment]
This has to do with your Nagios / Perl configuration. Where is your `Domain.pm` file? Is it in one of the listed directories?
