### ISSUE TITLE
Previously removed broken blacklists were added back

### ISSUE THREAD

**Issue by thomasvs** [matteocorti/check_rbl#26]
2bcc800042e81e2d732d09ebc8cedd6d8a16849e removed bl.spamcannibal.org which stopped working in 2018.

e00f050bcf3f435c136bec90a26f0328be381328 reintroduced it again with a vague message of "removed some slow checks".  It looks like that was not intended to happen.

Here are some specific suggestions to guard against this:

1) make the README.md and test.sh easier to read and update by breaking the single line of servers into one line per server, using \ as a continuation character.

2) maintain one master list of active blacklists, and generate the other files based off of that list.  It looks like the .ini file could serve as the master source of truth, to be updated in only one location, then generate test.sh and README.md from there.

**Comment by matteocorti** [comment]
I fixed the files. For the improvement I'll wait to find some time
