### ISSUE TITLE
More RBLs in check_rbl.ini

### ISSUE THREAD

**Issue by kepon85** [matteocorti/check_rbl#36]
Hello,

I found a lot of other RBLs on this page: http://multirbl.valli.org/list/ is there a reason they weren't implemented in the check_rbl.ini?

Thanks for this useful little script!

David

**Comment by magicdrums** [comment]
:O wait not all active RBL existing two list (Alive, Dead), Alive (345), Dead (523)

**Comment by kepon85** [comment]
> :O wait not all active RBL existing two list (Alive, Dead), Alive (345), Dead (523)

Not of course only the "Alive"

**Comment by kepon85** [comment]
No reason if not that nobody did the inventory work? (if this is the case I can do it but I wanted confirmation that there was no technical answer that I do not know ...)

**Comment by matteocorti** [comment]
I they work we can add them.

**Comment by matteocorti** [comment]
Fixed in 738aef3
