### ISSUE TITLE
use of check_rbl.ini

### ISSUE THREAD

**Issue by bieba** [matteocorti/check_rbl#39]
I try to unterstand the whole installation.
I already have set up the environment (Ubuntu 20.04) for the plugin, like descripted in the INSTALL doc.
Makefile, make and make install have run successful.

At the moment I am struggeling with the server option of the plugin. For simplicity I would like to grab the the servers from the ini file and pass them as the value to the plugin.

Is this the intended process? Or should I build a nice 'one liner' or simply a static input?

Thanks in advance.

**Comment by matteocorti** [comment]
You have both options:

1. Put all the servers in a file (e.g., ```check_rbl.ini```) and then specify it with the ```--extra-opts``` option. For example ```check_rbl -H corti.li --extra-opts=rbl@check_rbl.ini``` or
2. list all the RBL servers on the command line. For example ```check_rbl -H corti.li -s cbl.abuseat.org -s bl.deadbeef.com -s spamtrap.drbl.drand.net -s spamsources.fabel.dk -s 0spam.fusionzero.com -s mail-abuse.blacklist.jippg.org```
