### ISSUE TITLE
"Not a GLOB reference" error after p5-Net-DNS update

### ISSUE THREAD

**Issue by adam12b1** [matteocorti/check_rbl#4]
We've been using check_rbl happily for years, but after a minor update to other software including p5-Net-DNS (from 1.02 to 1.03), suddenly it threw this error:

   Not a GLOB reference at /usr/local/lib/perl5/5.20/mach/IO/Select.pm line 61.

I finally managed to fix it by editing line 61 in Select.pm, changing:
   $f = $f->[0] if ref($f) eq 'ARRAY';
to:
   $f = $f->[0];
but I don't actually understand this fix at all - just a lucky guess. :)

Command: "/usr/local/libexec/nagios/check_rbl --extra-opts=rbl@/usr/local/ee/check_rbl.ini -t 120 -H web.electricembers.net"

System: FreeBSD 10.1, Perl 5.20.3_8, check_rbl 1.3.0 or 1.3.7 (same issue with either version)

I don't know if this is a bug in Select.pm, or in p5-Net-DNS, or in check_rbl, or something else, but I'm hoping you will know better and be able to suggest or provide a more sustainable fix. (FYI I also had a lot of trouble managing the switch to requiring monitoring-plugins in check_rbl 1.3.7, because the Nagios package itself still requires nagios-plugins and the ports system won't install both at the same time because of overlapping files... but this is a separate issue, sorry.)

Hope you can help. Thanks!

**Comment by matteocorti** [comment]
I don't think that patching IO::Select would be a good idea. I will take a look at the issue

**Comment by matteocorti** [comment]
I can confirm the problem with Perl 5.22 and Net::DNS 1.03. I do not know yet if I have an error in my code (which is only exposed with this version) or if there is a bug in Perl or the Net::DNS module.

See http://stackoverflow.com/questions/33846179/not-a-glob-reference-at-io-select-pm-line-61

**Comment by matteocorti** [comment]
The problem is not a bug but is caused by a problem in Net::DNS 1.03. See [#108745: Net::DNS::Resolver bgsend](https://rt.cpan.org/Ticket/Display.html?id=108745)

Revert to a working version of the module.
