### ISSUE TITLE
feature: resolve monitored IP to hostname and show it in message

### ISSUE THREAD

**Issue by arekm** [matteocorti/check_rbl#40]
Such feature would be neat to have option that will turn on revdns resolving of monitored IP and report that additionally in message, so instead of:

````
CHECK_RBL WARNING - 1.2.3.4 BLACKLISTED on 1 server of 9 (b.barracudacentral.org) 
````

we would get

````
CHECK_RBL WARNING - 1.2.3.4 (reverse.name.example.com) BLACKLISTED on 1 server of 9 (b.barracudacentral.org)
````

Usage case:
monitoring for example entire /22 network and revdns contains information on for what that particular IP is actually used for.

**Comment by matteocorti** [comment]
I never implemented you can also invoke the script with the host name:

```
$ ./check_rbl -H corti.li -s cbl.abuseat.org
CHECK_RBL OK - corti.li BLACKLISTED on 0 servers of 1 | servers=0;0;0 time=0s;;
```

If you have a script iterating over IP addresses it could make sense. I'll take a look.

**Comment by arekm** [comment]
Yes, iterating over IPs here. Thanks!

btw. "corti.li BLACKLISTED" example is not that useful - IP is what's interesting (and also hostname could have tens of IP addresses). To get it useful (in generic case) it would have to report IP(s) in message itself and check all resolved IPs.

**Comment by matteocorti** [comment]
Implemented in 1.6.0

**Comment by arekm** [comment]
Thanks (will fail for ipv6 though - getnameinfo could be better for revdns handling)

**Comment by matteocorti** [comment]
Using ```getnameinfo```. Works with hostnames, IPv4 and IPv6

```
CHECK_RBL OK - 138.201.94.172 (corti.li) BLACKLISTED on 0 servers of 2 | servers=0;0;0 time=0s;;
CHECK_RBL OK - 2a01:4f8:c17:cbd8::1 (corti.li) BLACKLISTED on 0 servers of 2 | servers=0;0;0 time=0s;;
CHECK_RBL OK - corti.li BLACKLISTED on 0 servers of 2 | servers=0;0;0 time=0s;;
```

**Comment by matteocorti** [comment]
Released https://github.com/matteocorti/check_rbl/releases/tag/v1.6.1
