### ISSUE TITLE
IPv6 checks fail

### ISSUE THREAD

**Issue by heppel** [matteocorti/check_rbl#42]
IPv6 lookups against list.dnswl.org always return a "not listed" result. This can easily be verified by checking the address "::2". This is listed with a value of 127.0.10.0 on list.dnswl.org.

I found this, because my own IPv6 address is listed at dnswl.org, but check_rbl in whitelist mode returns an error.

The problem might affect blacklists as well.

xxxxxx@netsrv1:~$ dig +short 2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.list.dnswl.org
127.0.10.0

**Comment by matteocorti** [comment]
Which version are you using?

I get a different result:

```
./check_rbl -s list.dnswl.org -H ::2
CHECK_RBL OK - ::2 (::2) BLACKLISTED on 0 servers of 1 | servers=0;0;0 time=0s;
```

**Comment by heppel** [comment]
Thanks for fixing.
