### ISSUE TITLE
using FQDN breaks check

### ISSUE THREAD

**Issue by robje** [matteocorti/check_rbl#44]
When specifying an FQDN as `host` to check, the check fails.

This is because FQDN `host` ends in a dot ( . ) which gets concatenated with a dot and server-name. This results two consecutive dots in the name being looked up.

I can't find the code responsible for this concatenation (not to proficient in Perl). My short term solution is to add the following code on line 191 of version 1.6.2 from Debian repo
```
$name =~ s/\.\././;
```
This code replaces two dots with a single one.

This is right before
```
debug("reading...$name");
```

In my mind the better solution would be to either
1) always add the trailing dot and make `host` FQDN
or
2) strip trailing dots from `host before concatenating.

Preference is for 1. as non-FQDN hosts lookups in rbl do not make sense (at least to me).

**Comment by matteocorti** [comment]
I don't get why a FQDN should end in a dot: https://github.com/matteocorti/check_rbl/issues/44

**Comment by matteocorti** [comment]
I'll remove the dot ... https://serverfault.com/questions/803033/should-i-append-a-dot-at-the-end-of-my-dns-urls
