### ISSUE TITLE
BLACKLISTED on 2 servers of 153 (rep.mailspike.net (127.0.0.17) wl.mailspike.net (127.0.0.17)) but it is not 

### ISSUE THREAD

**Issue by 47k** [matteocorti/check_rbl#54]
Hey 

If I run this I got the error: 
BLACKLISTED on 2 servers of 153 (rep.mailspike.net (127.0.0.17) wl.mailspike.net (127.0.0.17))

But if I check on "https://mailspike.io/ip_verify" with the blacklisted IP, the page said: 
Possible legit sender
Your IP is good!

**Comment by matteocorti** [comment]
Without the IP I cannot test or reproduce the error. If you don't want to post it here, you can send it to me per email.

**Comment by matteocorti** [comment]
<img width="1457" alt="image" src="https://github.com/matteocorti/check_rbl/assets/6011536/da0989d5-f542-42fc-945d-477cc801f8c3">

The problem is that ```rep.mailspike.net``` uses an own coding for the responses.

**Comment by matteocorti** [comment]
I will remove it from the list of standard server. Supporting it would require a major rewrite.
