### ISSUE TITLE
Service flapping between blacklist and not blacklisted

### ISSUE THREAD

**Issue by 47k** [matteocorti/check_rbl#58]
Hello Matteo

Since maybe around 5-6 days we have some trouble with the script. Starting with blacklist flapping from "bondedsender.org". Because I can't found something about that blacklist, I deactivated the entries temporarily. 

After that we got the same issue with "bl.score.senderscore.com". So I think it's maybe an issue with check plugin. 

The service is flapping and generate a lot of output like mails. 

![image](https://github.com/user-attachments/assets/99fc3dc0-0393-4e4a-909b-7ccd3b9644b7)

Please let me know if you need further information 

Greetz
Manuel

**Comment by ssams** [comment]
I've also got check results on _bl.score.senderscore.com_, _plus.bondedsender.org_ , and _query.bondedsender.org_ since several days. Could be a problem with the respective lists, I've found some comments like https://forum.spamcop.net/topic/73357-internal-spamcop-handling-bondedsender/#comment-188903 that hint towards this.

**Comment by matteocorti** [comment]
bondedsender.org does not exist anymore

**Comment by matteocorti** [comment]
senderscore.com ist know for listing and delisting big blocks in short times.

**Comment by 47k** [comment]
@matteocorti 
About senderscore.com - do you mean that the blacklist entries and the flapping could be valid? I got this several times per day on several IPs in different ip ranges.

**Comment by matteocorti** [comment]
> @matteocorti About senderscore.com - do you mean that the blacklist entries and the flapping could be valid? I got this several times per day on several IPs in different ip ranges.
> 
> Here is an example output on one of my systems: ![image](https://private-user-images.githubusercontent.com/17850012/355033645-b20261ef-2b23-4a5e-9dda-910eb2b6b5fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDc5MTcsIm5iZiI6MTcyMjg0NzYxNywicGF0aCI6Ii8xNzg1MDAxMi8zNTUwMzM2NDUtYjIwMjYxZWYtMmIyMy00YTVlLTlkZGEtOTEwZWIyYjZiNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA4NDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhY2VhZWEwMDAxYWE1YzQwMzg4OWQyNDZiMjc4MzQ3YjFhMTAxMjc2NGViZGE1ZDhkNTBkMDYzNmRlZjcyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8u4DE1J7QMnhb3KsmPmp9sQTREdHFrNqgfLBgnt82M)

Seems so. I have seen several posts where they discuss the (bad) reputability of the service. I would exclude it from your configuration.

_Valid_ depends on the definition: the results are most likely flapping by senderscore, if you trust them, then yes the IPs are often blacklisted by a short time. If this information is really worth something depends on who is using senderscore.
