### ISSUE TITLE
Shipping version.pm not likely to be helpful.

### ISSUE THREAD

**Issue by kentfredric** [matteocorti/check_rbl#6]
This problem [was discovered](https://bugs.gentoo.org/show_bug.cgi?id=583966) in the tarball previously sourced from `https://svn.id.ethz.ch/projects/nagios_plugins/downloads/check_rbl-1.3.7.tar.gz`, which is now a redirect to a wiki page.

This problem is no longer present in the gtihub version of check_rbl, because it has a *different* copy of `version.pm`, but its presence is not much more helpful.

In the "Legacy" version of the shipped `version.pm`, it unhelpfully tries to require version::vpp and version::vxs, which *don't exist* on vanilla perls ( which is why [that block of code](https://metacpan.org/source/JPEACOCK/version-0.9912/lib/version.pm#L16-58) gets nuked in core ), but they *do* exist if you've upgraded to a `version.pm` on CPAN.

Which leads to this problem if you ship a CPAN-targeted copy of `version.pm` on a vanilla perl:

```shell
 perl -Iinc -Mversion -E1 
# Can't locate version/vpp.pm in @INC (you may need to install the version::vpp module) (@INC contains: inc /etc/perl /usr/local/lib64/perl5/5.24.0/x86_64-linux /usr/local/lib64/perl5/5.24.0 /usr/lib64/perl5/vendor_perl/5.24.0/x86_64-linux /usr/lib64/perl5/vendor_perl/5.24.0 /usr/lib64/perl5/5.24.0/x86_64-linux /usr/lib64/perl5/5.24.0 .) at (eval 2) line 1.
# BEGIN failed--compilation aborted at (eval 2) line 1.
# Compilation failed in require.
# BEGIN failed--compilation aborted.
```

And this ulitimately leads to a cascade of other problems getting hidden, and eventually resulting in:

```shell
perl -Iinc -MExtUtils::MakeMaker -E1 
# Can't locate ExtUtils/MakeMaker/version/vpp.pm in @INC (you may need to install the ExtUtils::MakeMaker::version::vpp module) (@INC contains: inc /etc/perl /usr/local/lib64/perl5/5.24.0/x86_64-linux /usr/local/lib64/perl5/5.24.0 /usr/lib64/perl5/vendor_perl/5.24.0/x86_64-linux /usr/lib64/perl5/vendor_perl/5.24.0 /usr/lib64/perl5/5.24.0/x86_64-linux /usr/lib64/perl5/5.24.0 .) at (eval 4) line 2.
# BEGIN failed--compilation aborted at (eval 4) line 2.
# Compilation failed in require at /usr/lib64/perl5/5.24.0/ExtUtils/MakeMaker.pm line 10.
# BEGIN failed--compilation aborted at /usr/lib64/perl5/5.24.0/ExtUtils/MakeMaker.pm line 10.
# Compilation failed in require.
# BEGIN failed--compilation aborted.
```

Because, of *course* EUMM doesn't need its bundled vpp on core perl :/ 

Its possible you're already aware of this problem and have already taken steps to resolve it in some way, as possibly evidenced by the different `version.pm` in the github sources.

However, I'm filing this bug anyway *just* to be sure, because even the "fixed" version of `version.pm` doesn't really solve any problems by being there, it *cannot* do anything useful on its own.

The "bundled" version of `version.pm` essentially relies on the fact perl automatically defines the entire `version::` namespace *without* loading modules, and it just adds an `import` interface to export those functions (however they are defined) into the users code.

Its probably just best to not ship `version.pm` in inc/ at all, because it doesn't really give you much as far as I can see. After all, [`ExtUtils::MakeMaker` already requires `version.pm`](https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-7.18/lib/ExtUtils/MakeMaker/version.pm#L24) and has its own way of solving the problems there in the right way, and shipping your own copy of `version.pm` is unlikely to be of any use.

Especially given the `version.pm` you're shipping will still require some other module that is also part of the `version.pm` dist ( or part of core ), but you're not shipping. ( ie: version::regex ).

Its safer to just assume consumers without a copy of `version.pm` have unresolvably broken setups that should be resolved before attempting to install your software. ( Due to all the internals you're relying on also using version.pm anyway )

If, however, you had a bug that indicated you should bundle `version.pm`, I would like to see it to rule out any other possible things I haven't considered in my recommendation against bundling.

**Comment by matteocorti** [comment]
Fixed in 1.3.8.
